name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Check out code into the Go module directory
        run: mkdir -p ./go/src/github.com/ $ GITHUB_REPOSITORY && cp -r ./* ./go/src/github.com/ $ GITHUB_REPOSITORY/

      - name: Build
        run: cd ./go/src/github.com/ $ GITHUB_REPOSITORY/ && go build -v ./...